{
   "views" : {
      "recommend" : {
         "map" : "            function (doc) {\n                val = {};\n                val[doc.similar] = doc.relevance;\n                emit(doc.distribution, val);\n            }\n",
         "reduce" : "            function (keys, values, rereduce) {\n                var rv = {};\n                for (i in values) {\n                    var value = values[i];\n                    for (k in value) {\n                        rv[k] = value[k];\n                    }\n                }\n                return rv;\n            }\n"
      }
   },
   "lists" : {
      "top" : "        function (head, req) {\n            function rank_sort(keys, vals) {\n                return keys.sort(function (b, a) {\n                    var delta = vals[a] - vals[b];\n                    if (delta) {\n                        return delta;\n                    } else if (a > b) {\n                        return -1;\n                    } else if (a < b) {\n                        return 1;\n                    } else {\n                        return 0;\n                    }\n                });\n            }\n\n            var result = [];\n            var row;\n            while (row = getRow()) {\n                var names = [];\n                for (var name in row.value) {\n                    if (row.value.hasOwnProperty(name)) {\n                        names.push(name);\n                    }\n                }\n\n                var slice = {};\n                names = rank_sort(names, row.value).splice(0, 10).sort();\n                for (var i = 0; i < names.length; i++) {\n                    slice[names[i]] = row.value[names[i]];\n                }\n\n                result.push({\n                    \"key\": row.key,\n                    \"value\": slice\n                });\n            }\n\n            var json = JSON.stringify({\"rows\": result});\n\n            if (typeof(req.query['callback']) === 'undefined') {\n                send(json + \"\\n\");\n            } else {\n                send(req.query.callback + '(' + json + \");\\n\");\n            }\n        }\n",
      "user" : "        function (head, req) {\n            var stop = {};\n\n            try {\n                var own = eval(req.query['keys']);\n                for (var i = 0; i < own.length; i++) {\n                    stop[own[i]] = 1;\n                }\n            } catch(e) {\n            }\n\n            var bag = {};\n            var row;\n            while (row = getRow()) {\n                for (var similar in row.value) {\n                    if (row.value.hasOwnProperty(similar) && typeof(stop[similar]) === 'undefined') {\n                        if (typeof(bag[similar]) === 'undefined') {\n                            bag[similar] = 1;\n                        } else {\n                            bag[similar]++;\n                        }\n                    }\n                }\n            }\n\n            function rank_sort(keys, vals) {\n                return keys.sort(function (b, a) {\n                    var delta = vals[a] - vals[b];\n                    if (delta) {\n                        return delta;\n                    } else if (a > b) {\n                        return -1;\n                    } else if (a < b) {\n                        return 1;\n                    } else {\n                        return 0;\n                    }\n                });\n            }\n\n            var top_dists = [];\n            for (var word in bag) {\n                if (bag.hasOwnProperty(word) && bag[word] > 0) {\n                    top_dists.push(word);\n                }\n            }\n\n            var json = JSON.stringify({\n                \"rows\": rank_sort(top_dists, bag).map(function (name) {\n                    return {\n                        \"key\": name,\n                        \"value\": bag[name]\n                    };\n                })\n            });\n\n            if (typeof(req.query['callback']) === 'undefined') {\n                send(json + \"\\n\");\n            } else {\n                send(req.query.callback + '(' + json + \");\\n\");\n            }\n        }\n"
   },
   "_id" : "_design/recommend",
   "_rev" : "35-e9b177e79186d06f41947490cbee8606"
}
